# Generated by Django 4.2.5 on 2023-11-05 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.BinaryField()),
                ('name', models.CharField()),
                ('size', models.IntegerField()),
                ('file_name', models.CharField()),
                ('charset', models.CharField()),
                ('content_type', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=300)),
                ('password', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Shared',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_date', models.DateTimeField(auto_now_add=True)),
                ('password', models.BinaryField(null=True)),
                ('shared_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.files')),
                ('shared_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.user')),
            ],
        ),
        migrations.AddField(
            model_name='files',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud.user'),
        ),
    ]
