# Generated by Django 4.2.5 on 2023-11-05 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_alter_files_charset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shared',
            name='password',
        ),
    ]
